#coding=utf-8

#import libs 
import JSQ_cmd
import JSQ_sty
import Fun
import tkinter
from   tkinter import *
import tkinter.ttk
import tkinter.font
G_VarArray=[['Count',0]]
#Add your Varial Here: (Keep This Line of comments)
#Define UI Class
class  JSQ:
    def __init__(self,root,isTKroot = True):
        uiName = self.__class__.__name__
        Fun.G_UIElementArray[uiName]={}
        Fun.G_UIElementUserDataArray[uiName]={}
        Fun.Register(uiName,'UIClass',self)
        self.root = root
        style = JSQ_sty.SetupStyle()
        if isTKroot == True:
            root.title("Form1")
            Fun.CenterDlg(uiName,root,222,216)
        Form_1= tkinter.Canvas(root,width = 10,height = 4)
        Form_1.place(x = 0,y = 0,width = 222,height = 216)
        Form_1.configure(bg = "#efefef")
        Form_1.configure(highlightthickness = 0)
        Fun.Register(uiName,'root',root)
        Fun.Register(uiName,'Form_1',Form_1)
        #Create the elements of root 
        Label_2= tkinter.Label(root,text="",width = 10,height = 4)
        Label_2.place(x = 12,y = 13,width = 190,height = 30)
        Label_2.configure(bg = "#808080")
        Label_2.configure(fg = "#ffffff")
        Label_2.configure(relief = "flat")
        Fun.AddUserData(uiName,'Label_2','Count','float',0.0,1)
        Fun.AddUserData(uiName,'Label_2','MidCount','float',0.0,0)
        Fun.AddUserData(uiName,'Label_2','OpType','int',0,0)
        Fun.Register(uiName,'Label_2',Label_2)
        Button_3= tkinter.Button(root,text="1",width = 10,height = 4)
        Button_3.place(x = 10,y = 50,width = 40,height = 30)
        Button_3.configure(relief = "groove")
        Button_3.configure(command=lambda:JSQ_cmd.Button_3_onCommand(uiName,"Button_3"))
        Fun.Register(uiName,'Button_3',Button_3)
        Button_4= tkinter.Button(root,text="2",width = 10,height = 4)
        Button_4.place(x = 60,y = 50,width = 40,height = 30)
        Button_4.configure(relief = "groove")
        Button_4.configure(command=lambda:JSQ_cmd.Button_4_onCommand(uiName,"Button_4"))
        Fun.Register(uiName,'Button_4',Button_4)
        Button_5= tkinter.Button(root,text="3",width = 10,height = 4)
        Button_5.place(x = 110,y = 50,width = 40,height = 30)
        Button_5.configure(relief = "groove")
        Button_5.configure(command=lambda:JSQ_cmd.Button_5_onCommand(uiName,"Button_5"))
        Fun.Register(uiName,'Button_5',Button_5)
        Button_6= tkinter.Button(root,text="4",width = 10,height = 4)
        Button_6.place(x = 10,y = 90,width = 40,height = 30)
        Button_6.configure(relief = "groove")
        Button_6.configure(command=lambda:JSQ_cmd.Button_6_onCommand(uiName,"Button_6"))
        Fun.Register(uiName,'Button_6',Button_6)
        Button_7= tkinter.Button(root,text="5",width = 10,height = 4)
        Button_7.place(x = 60,y = 90,width = 40,height = 30)
        Button_7.configure(relief = "groove")
        Button_7.configure(command=lambda:JSQ_cmd.Button_7_onCommand(uiName,"Button_7"))
        Fun.Register(uiName,'Button_7',Button_7)
        Button_8= tkinter.Button(root,text="6",width = 10,height = 4)
        Button_8.place(x = 110,y = 90,width = 40,height = 30)
        Button_8.configure(relief = "groove")
        Button_8.configure(command=lambda:JSQ_cmd.Button_8_onCommand(uiName,"Button_8"))
        Fun.Register(uiName,'Button_8',Button_8)
        Button_9= tkinter.Button(root,text="7",width = 10,height = 4)
        Button_9.place(x = 10,y = 130,width = 40,height = 30)
        Button_9.configure(relief = "groove")
        Button_9.configure(command=lambda:JSQ_cmd.Button_9_onCommand(uiName,"Button_9"))
        Fun.Register(uiName,'Button_9',Button_9)
        Button_10= tkinter.Button(root,text="8",width = 10,height = 4)
        Button_10.place(x = 60,y = 130,width = 40,height = 30)
        Button_10.configure(relief = "groove")
        Button_10.configure(command=lambda:JSQ_cmd.Button_10_onCommand(uiName,"Button_10"))
        Fun.Register(uiName,'Button_10',Button_10)
        Button_11= tkinter.Button(root,text="9",width = 10,height = 4)
        Button_11.place(x = 110,y = 130,width = 40,height = 30)
        Button_11.configure(relief = "groove")
        Button_11.configure(command=lambda:JSQ_cmd.Button_11_onCommand(uiName,"Button_11"))
        Fun.Register(uiName,'Button_11',Button_11)
        Button_12= tkinter.Button(root,text="0",width = 10,height = 4)
        Button_12.place(x = 10,y = 170,width = 40,height = 30)
        Button_12.configure(relief = "groove")
        Button_12.configure(command=lambda:JSQ_cmd.Button_12_onCommand(uiName,"Button_12"))
        Fun.Register(uiName,'Button_12',Button_12)
        Button_13= tkinter.Button(root,text="C",width = 10,height = 4)
        Button_13.place(x = 60,y = 170,width = 40,height = 30)
        Button_13.configure(relief = "groove")
        Button_13.configure(command=lambda:JSQ_cmd.Button_13_onCommand(uiName,"Button_13"))
        Fun.Register(uiName,'Button_13',Button_13)
        Button_14= tkinter.Button(root,text="=",width = 10,height = 4)
        Button_14.place(x = 110,y = 169,width = 40,height = 30)
        Button_14.configure(relief = "groove")
        Button_14.configure(command=lambda:JSQ_cmd.Button_14_onCommand(uiName,"Button_14"))
        Fun.Register(uiName,'Button_14',Button_14)
        Button_15= tkinter.Button(root,text="+",width = 10,height = 4)
        Button_15.place(x = 160,y = 50,width = 40,height = 30)
        Button_15.configure(relief = "groove")
        Button_15.configure(command=lambda:JSQ_cmd.Button_15_onCommand(uiName,"Button_15"))
        Fun.Register(uiName,'Button_15',Button_15)
        Button_16= tkinter.Button(root,text="-",width = 10,height = 4)
        Button_16.place(x = 160,y = 90,width = 40,height = 30)
        Button_16.configure(relief = "groove")
        Button_16.configure(command=lambda:JSQ_cmd.Button_16_onCommand(uiName,"Button_16"))
        Fun.Register(uiName,'Button_16',Button_16)
        Button_17= tkinter.Button(root,text="X",width = 10,height = 4)
        Button_17.place(x = 160,y = 130,width = 40,height = 30)
        Button_17.configure(relief = "groove")
        Button_17.configure(command=lambda:JSQ_cmd.Button_17_onCommand(uiName,"Button_17"))
        Fun.Register(uiName,'Button_17',Button_17)
        Button_18= tkinter.Button(root,text="/",width = 10,height = 4)
        Button_18.place(x = 160,y = 170,width = 40,height = 30)
        Button_18.configure(relief = "groove")
        Button_18.configure(command=lambda:JSQ_cmd.Button_18_onCommand(uiName,"Button_18"))
        Fun.Register(uiName,'Button_18',Button_18)
        #Create the Menu of root 
        MainMenu=tkinter.Menu(root)
        root.config(menu = MainMenu)
        A=tkinter.Menu(MainMenu,tearoff = 0)
        A1=tkinter.Menu(A,tearoff = 0)
        A1.add_command(label="A11",command=lambda:JSQ_cmd.Menu_A11(uiName,"A11"))
        A.add_cascade(label="A1",menu=A1)
        MainMenu.add_cascade(label="A",menu=A)
        B=tkinter.Menu(MainMenu,tearoff = 0)
        B.add_command(label="B3",command=lambda:JSQ_cmd.Menu_B3(uiName,"B3"))
        B.add_command(label="B2",command=lambda:JSQ_cmd.Menu_B2(uiName,"B2"))
        MainMenu.add_cascade(label="B",menu=B)
        #Inital all element's Data 
        Fun.InitElementData(uiName)
        #Add Some Logic Code Here: (Keep This Line of comments)


#Create the root of Kinter 
if  __name__ == '__main__':
    root = tkinter.Tk()
    MyDlg = JSQ(root)
    root.mainloop()
